# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/src/MarsZX3_EB1.xdc

# Block Designs: bd/MarsZX3/MarsZX3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3 || ORIG_REF_NAME==MarsZX3} -quiet] -quiet

# IP: bd/MarsZX3/ip/MarsZX3_axi_gpio_0_0/MarsZX3_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_axi_gpio_0_0 || ORIG_REF_NAME==MarsZX3_axi_gpio_0_0} -quiet] -quiet

# IP: bd/MarsZX3/ip/MarsZX3_processing_system7_0_0/MarsZX3_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_processing_system7_0_0 || ORIG_REF_NAME==MarsZX3_processing_system7_0_0} -quiet] -quiet

# IP: bd/MarsZX3/ip/MarsZX3_processing_system7_0_axi_periph_0/MarsZX3_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==MarsZX3_processing_system7_0_axi_periph_0} -quiet] -quiet

# IP: bd/MarsZX3/ip/MarsZX3_rst_processing_system7_0_50M_0/MarsZX3_rst_processing_system7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==MarsZX3_rst_processing_system7_0_50M_0} -quiet] -quiet

# IP: bd/MarsZX3/ip/MarsZX3_xlconstant_0_1/MarsZX3_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_xlconstant_0_1 || ORIG_REF_NAME==MarsZX3_xlconstant_0_1} -quiet] -quiet

# IP: bd/MarsZX3/ip/MarsZX3_axi_mem_intercon_0/MarsZX3_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_axi_mem_intercon_0 || ORIG_REF_NAME==MarsZX3_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/MarsZX3/ip/MarsZX3_xbar_0/MarsZX3_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_xbar_0 || ORIG_REF_NAME==MarsZX3_xbar_0} -quiet] -quiet

# IP: bd/MarsZX3/ip/MarsZX3_axi_vdma_0_1/MarsZX3_axi_vdma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_axi_vdma_0_1 || ORIG_REF_NAME==MarsZX3_axi_vdma_0_1} -quiet] -quiet

# IP: bd/MarsZX3/ip/MarsZX3_DCMI_VDMA_Bridge_0_2/MarsZX3_DCMI_VDMA_Bridge_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_DCMI_VDMA_Bridge_0_2 || ORIG_REF_NAME==MarsZX3_DCMI_VDMA_Bridge_0_2} -quiet] -quiet

# IP: bd/MarsZX3/ip/MarsZX3_HDPYX_DCMI_Bridge_0_1/MarsZX3_HDPYX_DCMI_Bridge_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_HDPYX_DCMI_Bridge_0_1 || ORIG_REF_NAME==MarsZX3_HDPYX_DCMI_Bridge_0_1} -quiet] -quiet

# IP: bd/MarsZX3/ip/MarsZX3_HDPYX_Emulator_0_0/MarsZX3_HDPYX_Emulator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_HDPYX_Emulator_0_0 || ORIG_REF_NAME==MarsZX3_HDPYX_Emulator_0_0} -quiet] -quiet

# IP: bd/MarsZX3/ip/MarsZX3_xlconstant_0_2/MarsZX3_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_xlconstant_0_2 || ORIG_REF_NAME==MarsZX3_xlconstant_0_2} -quiet] -quiet

# IP: bd/MarsZX3/ip/MarsZX3_xbar_1/MarsZX3_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_xbar_1 || ORIG_REF_NAME==MarsZX3_xbar_1} -quiet] -quiet

# IP: bd/MarsZX3/ip/MarsZX3_DCMI_VDMA_Bridge_0_3/MarsZX3_DCMI_VDMA_Bridge_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_DCMI_VDMA_Bridge_0_3 || ORIG_REF_NAME==MarsZX3_DCMI_VDMA_Bridge_0_3} -quiet] -quiet

# IP: bd/MarsZX3/ip/MarsZX3_HDPYX_DCMI_Bridge_0_2/MarsZX3_HDPYX_DCMI_Bridge_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_HDPYX_DCMI_Bridge_0_2 || ORIG_REF_NAME==MarsZX3_HDPYX_DCMI_Bridge_0_2} -quiet] -quiet

# IP: bd/MarsZX3/ip/MarsZX3_HDPYX_DCMI_Bridge_1_0/MarsZX3_HDPYX_DCMI_Bridge_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_HDPYX_DCMI_Bridge_1_0 || ORIG_REF_NAME==MarsZX3_HDPYX_DCMI_Bridge_1_0} -quiet] -quiet

# IP: bd/MarsZX3/ip/MarsZX3_DCMI_VDMA_Bridge_1_0/MarsZX3_DCMI_VDMA_Bridge_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_DCMI_VDMA_Bridge_1_0 || ORIG_REF_NAME==MarsZX3_DCMI_VDMA_Bridge_1_0} -quiet] -quiet

# IP: bd/MarsZX3/ip/MarsZX3_axi_vdma_0_2/MarsZX3_axi_vdma_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_axi_vdma_0_2 || ORIG_REF_NAME==MarsZX3_axi_vdma_0_2} -quiet] -quiet

# IP: bd/MarsZX3/ip/MarsZX3_axi_vdma_1_0/MarsZX3_axi_vdma_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_axi_vdma_1_0 || ORIG_REF_NAME==MarsZX3_axi_vdma_1_0} -quiet] -quiet

# IP: bd/MarsZX3/ip/MarsZX3_xlconcat_0_1/MarsZX3_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_xlconcat_0_1 || ORIG_REF_NAME==MarsZX3_xlconcat_0_1} -quiet] -quiet

# IP: bd/MarsZX3/ip/MarsZX3_DCMI_COUNTER_0_0/MarsZX3_DCMI_COUNTER_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_DCMI_COUNTER_0_0 || ORIG_REF_NAME==MarsZX3_DCMI_COUNTER_0_0} -quiet] -quiet

# IP: bd/MarsZX3/ip/MarsZX3_DCMI_COUNTER_0_1/MarsZX3_DCMI_COUNTER_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_DCMI_COUNTER_0_1 || ORIG_REF_NAME==MarsZX3_DCMI_COUNTER_0_1} -quiet] -quiet

# IP: bd/MarsZX3/ip/MarsZX3_DCMI_COUNTER_1_0/MarsZX3_DCMI_COUNTER_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_DCMI_COUNTER_1_0 || ORIG_REF_NAME==MarsZX3_DCMI_COUNTER_1_0} -quiet] -quiet

# IP: bd/MarsZX3/ip/MarsZX3_rst_system7_0_50M_0/MarsZX3_rst_system7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_rst_system7_0_50M_0 || ORIG_REF_NAME==MarsZX3_rst_system7_0_50M_0} -quiet] -quiet

# IP: bd/MarsZX3/ip/MarsZX3_HDPYX_Emulator_PLAIN_0_0/MarsZX3_HDPYX_Emulator_PLAIN_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_HDPYX_Emulator_PLAIN_0_0 || ORIG_REF_NAME==MarsZX3_HDPYX_Emulator_PLAIN_0_0} -quiet] -quiet

# IP: bd/MarsZX3/ip/MarsZX3_HDPYX_Emulator_STRIP_0_0/MarsZX3_HDPYX_Emulator_STRIP_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_HDPYX_Emulator_STRIP_0_0 || ORIG_REF_NAME==MarsZX3_HDPYX_Emulator_STRIP_0_0} -quiet] -quiet

# IP: bd/MarsZX3/ip/MarsZX3_auto_pc_0/MarsZX3_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_auto_pc_0 || ORIG_REF_NAME==MarsZX3_auto_pc_0} -quiet] -quiet

# IP: bd/MarsZX3/ip/MarsZX3_auto_pc_1/MarsZX3_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_auto_pc_1 || ORIG_REF_NAME==MarsZX3_auto_pc_1} -quiet] -quiet

# XDC: bd/MarsZX3/MarsZX3_ooc.xdc
