# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_msg_config  -severity {WARNING}  -suppress 
set_msg_config  -id {DRC 23-20}  -string {{CRITICAL WARNING: [DRC 23-20] Rule violation (IOSTDTYPE-1) IOStandard Type - I/O port CAM0_XCLK_N is Single-Ended but has an IOStandard of LVDS_25 which can only support Differential}}  -suppress 
set_msg_config  -id {DRC 23-20}  -string {{CRITICAL WARNING: [DRC 23-20] Rule violation (IOSTDTYPE-1) IOStandard Type - I/O port CAM0_XCLK_P is Single-Ended but has an IOStandard of LVDS_25 which can only support Differential}}  -suppress 
set_msg_config  -id {DRC 23-20}  -string {{CRITICAL WARNING: [DRC 23-20] Rule violation (IOSTDTYPE-1) IOStandard Type - I/O port CAM1_XYCLK_N is Single-Ended but has an IOStandard of LVDS_25 which can only support Differential}}  -suppress 
set_msg_config  -id {DRC 23-20}  -string {{CRITICAL WARNING: [DRC 23-20] Rule violation (IOSTDTYPE-1) IOStandard Type - I/O port CAM1_XYCLK_P is Single-Ended but has an IOStandard of LVDS_25 which can only support Differential}}  -suppress 
set_msg_config  -id {Synth 8-2029}  -string {{ERROR: [Synth 8-2029] formal data_bank_b_p has no actual or default value [E:/Vivado/MEB1/src/system_top_EB1.vhd:331]}}  -suppress 
set_msg_config  -id {Common 17-69}  -string {{ERROR: [Common 17-69] Command failed: Synthesis failed - please see the console or run log file for details}}  -suppress 
set_msg_config  -id {Timing 38-282}  -string {{CRITICAL WARNING: [Timing 38-282] The design failed to meet the timing requirements. Please see the timing summary report for details on the timing violations.}}  -suppress 
set_msg_config  -id {filemgmt 20-1788}  -string {{ERROR: [filemgmt 20-1788] Illegal access of HADGNode between graph update events.}}  -suppress 
set_msg_config  -id {filemgmt 56-23}  -string {{ERROR: [filemgmt 56-23] Illegal GUI graph access between updates.}}  -suppress 
set_msg_config  -id {Place 30-574}  -suppress 
set_msg_config  -id {BD 41-967}  -suppress 
set_msg_config  -id {IP_Flow 19-4965}  -suppress 
set_msg_config  -id {Common 17-55}  -suppress 
set_msg_config  -id {Common 17-1355}  -suppress 
set_msg_config  -id {Place 30-378}  -string {{ERROR: [Place 30-378] Input pin of input buffer i_system/selectio_bank_a/inst/ibufds_clk_inst has an illegal connection to a logic constant value.}}  -suppress 
set_msg_config  -id {BD 41-759}  -string {{CRITICAL WARNING: [BD 41-759] The input pins (listed below) are either not connected or do not have a source port, and they don't have a tie-off specified. These pins are tied-off to all 0's to avoid error in Implementation flow.
Please check your design and connect them as needed: 
/HDPyx_TPG_0/start
/HDPyx_TPG_1/start}}  -suppress 
set_msg_config  -id {DRC 23-20}  -string {{ERROR: [DRC 23-20] Rule violation (BIVC-1) Bank IO standard Vcc - Conflicting Vcc voltages in bank 35. For example, the following two ports in this bank have conflicting VCCOs:  
DATA_BANK_A_P[0] (LVCMOS18, requiring VCCO=1.800) and Led_N[0] (LVCMOS25, requiring VCCO=2.500)}}  -suppress 
set_msg_config  -id {Vivado_Tcl 4-23}  -string {{ERROR: [Vivado_Tcl 4-23] Error(s) found during DRC. Placer not run.}}  -suppress 
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.cache/wt [current_project]
set_property parent.project_path C:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths {
  c:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/ips/HDPyx_DDR_To_AXI_zybo
  c:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/ips/HDPyx_TPG
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/src/system_top_EB1.vhd
add_files C:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/MarsZX3.bd
set_property used_in_implementation false [get_files -all c:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_gpio_0_0/MarsZX3_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_gpio_0_0/MarsZX3_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_gpio_0_0/MarsZX3_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_processing_system7_0_0/MarsZX3_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_rst_processing_system7_0_50M_0/MarsZX3_rst_processing_system7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_rst_processing_system7_0_50M_0/MarsZX3_rst_processing_system7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all c:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_rst_processing_system7_0_50M_0/MarsZX3_rst_processing_system7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_xbar_0/MarsZX3_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_vdma_0_1/MarsZX3_axi_vdma_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_vdma_0_1/MarsZX3_axi_vdma_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_vdma_0_1/MarsZX3_axi_vdma_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_xbar_1/MarsZX3_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_vdma_0_2/MarsZX3_axi_vdma_0_2.xdc]
set_property used_in_implementation false [get_files -all c:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_vdma_0_2/MarsZX3_axi_vdma_0_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_vdma_0_2/MarsZX3_axi_vdma_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_vdma_1_0/MarsZX3_axi_vdma_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_vdma_1_0/MarsZX3_axi_vdma_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_vdma_1_0/MarsZX3_axi_vdma_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_rst_system7_0_50M_0/MarsZX3_rst_system7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_rst_system7_0_50M_0/MarsZX3_rst_system7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all c:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_rst_system7_0_50M_0/MarsZX3_rst_system7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_auto_pc_0/MarsZX3_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_auto_pc_1/MarsZX3_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/MarsZX3_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/src/MarsZX3_EB1.xdc
set_property used_in_implementation false [get_files C:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/src/MarsZX3_EB1.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top system_top -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_top.dcp
create_report "MarsEB1_synth_synth_report_utilization_0" "report_utilization -file system_top_utilization_synth.rpt -pb system_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
