# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
set_msg_config  -severity {WARNING}  -suppress 
set_msg_config  -id {DRC 23-20}  -string {{CRITICAL WARNING: [DRC 23-20] Rule violation (IOSTDTYPE-1) IOStandard Type - I/O port CAM0_XCLK_N is Single-Ended but has an IOStandard of LVDS_25 which can only support Differential}}  -suppress 
set_msg_config  -id {DRC 23-20}  -string {{CRITICAL WARNING: [DRC 23-20] Rule violation (IOSTDTYPE-1) IOStandard Type - I/O port CAM0_XCLK_P is Single-Ended but has an IOStandard of LVDS_25 which can only support Differential}}  -suppress 
set_msg_config  -id {DRC 23-20}  -string {{CRITICAL WARNING: [DRC 23-20] Rule violation (IOSTDTYPE-1) IOStandard Type - I/O port CAM1_XYCLK_N is Single-Ended but has an IOStandard of LVDS_25 which can only support Differential}}  -suppress 
set_msg_config  -id {DRC 23-20}  -string {{CRITICAL WARNING: [DRC 23-20] Rule violation (IOSTDTYPE-1) IOStandard Type - I/O port CAM1_XYCLK_P is Single-Ended but has an IOStandard of LVDS_25 which can only support Differential}}  -suppress 
set_msg_config  -id {Synth 8-2029}  -string {{ERROR: [Synth 8-2029] formal data_bank_b_p has no actual or default value [E:/Vivado/MEB1/src/system_top_EB1.vhd:331]}}  -suppress 
set_msg_config  -id {Common 17-69}  -string {{ERROR: [Common 17-69] Command failed: Synthesis failed - please see the console or run log file for details}}  -suppress 
set_msg_config  -id {Timing 38-282}  -string {{CRITICAL WARNING: [Timing 38-282] The design failed to meet the timing requirements. Please see the timing summary report for details on the timing violations.}}  -suppress 
set_msg_config  -id {filemgmt 20-1788}  -string {{ERROR: [filemgmt 20-1788] Illegal access of HADGNode between graph update events.}}  -suppress 
set_msg_config  -id {filemgmt 56-23}  -string {{ERROR: [filemgmt 56-23] Illegal GUI graph access between updates.}}  -suppress 
set_msg_config  -id {BD 41-967}  -suppress 
set_msg_config  -id {IP_Flow 19-4965}  -suppress 
set_msg_config  -id {Common 17-55}  -suppress 
set_msg_config  -id {Common 17-1355}  -suppress 
set_msg_config  -id {Place 30-378}  -string {{ERROR: [Place 30-378] Input pin of input buffer i_system/selectio_bank_a/inst/ibufds_clk_inst has an illegal connection to a logic constant value.}}  -suppress 
set_msg_config  -id {BD 41-759}  -string {{CRITICAL WARNING: [BD 41-759] The input pins (listed below) are either not connected or do not have a source port, and they don't have a tie-off specified. These pins are tied-off to all 0's to avoid error in Implementation flow.
Please check your design and connect them as needed: 
/HDPyx_TPG_0/start
/HDPyx_TPG_1/start}}  -suppress 
set_msg_config  -id {DRC 23-20}  -string {{ERROR: [DRC 23-20] Rule violation (BIVC-1) Bank IO standard Vcc - Conflicting Vcc voltages in bank 35. For example, the following two ports in this bank have conflicting VCCOs:  
DATA_BANK_A_P[0] (LVCMOS18, requiring VCCO=1.800) and Led_N[0] (LVCMOS25, requiring VCCO=2.500)}}  -suppress 
set_msg_config  -id {Vivado_Tcl 4-23}  -string {{ERROR: [Vivado_Tcl 4-23] Error(s) found during DRC. Placer not run.}}  -suppress 
set_param project.vivado.isBlockSynthRun true
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.cache/wt [current_project]
set_property parent.project_path C:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths {
  c:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_3SENSORS_modif/ips/HDPyx_DDR_To_AXI_zybo
  c:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_3SENSORS_modif/ips/HDPyx_TPG
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/FMa/ATISE/Development/Clean_ENV/RTL/HDPYX_DCMI_Bridge.vhd
read_ip -quiet C:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_HDPYX_DCMI_Bridge_0_1/MarsZX3_HDPYX_DCMI_Bridge_0_1.xci

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1

set cached_ip [config_ip_cache -export -no_bom  -dir C:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.runs/MarsZX3_HDPYX_DCMI_Bridge_0_1_synth_1 -new_name MarsZX3_HDPYX_DCMI_Bridge_0_1 -ip [get_ips MarsZX3_HDPYX_DCMI_Bridge_0_1]]

if { $cached_ip eq {} } {
close [open __synthesis_is_running__ w]

synth_design -top MarsZX3_HDPYX_DCMI_Bridge_0_1 -part xc7z020clg484-1 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
# disable binary constraint mode for IPCache checkpoints
set_param constraints.enableBinaryConstraints false

catch {
 write_checkpoint -force -noxdef -rename_prefix MarsZX3_HDPYX_DCMI_Bridge_0_1_ MarsZX3_HDPYX_DCMI_Bridge_0_1.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ MarsZX3_HDPYX_DCMI_Bridge_0_1_stub.v
 lappend ipCachedFiles MarsZX3_HDPYX_DCMI_Bridge_0_1_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ MarsZX3_HDPYX_DCMI_Bridge_0_1_stub.vhdl
 lappend ipCachedFiles MarsZX3_HDPYX_DCMI_Bridge_0_1_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ MarsZX3_HDPYX_DCMI_Bridge_0_1_sim_netlist.v
 lappend ipCachedFiles MarsZX3_HDPYX_DCMI_Bridge_0_1_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ MarsZX3_HDPYX_DCMI_Bridge_0_1_sim_netlist.vhdl
 lappend ipCachedFiles MarsZX3_HDPYX_DCMI_Bridge_0_1_sim_netlist.vhdl
set TIME_taken [expr [clock seconds] - $TIME_start]

 config_ip_cache -add -dcp MarsZX3_HDPYX_DCMI_Bridge_0_1.dcp -move_files $ipCachedFiles -use_project_ipc  -synth_runtime $TIME_taken  -ip [get_ips MarsZX3_HDPYX_DCMI_Bridge_0_1]
}

rename_ref -prefix_all MarsZX3_HDPYX_DCMI_Bridge_0_1_

# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MarsZX3_HDPYX_DCMI_Bridge_0_1.dcp
create_report "MarsZX3_HDPYX_DCMI_Bridge_0_1_synth_1_synth_report_utilization_0" "report_utilization -file MarsZX3_HDPYX_DCMI_Bridge_0_1_utilization_synth.rpt -pb MarsZX3_HDPYX_DCMI_Bridge_0_1_utilization_synth.pb"

if { [catch {
  file copy -force C:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.runs/MarsZX3_HDPYX_DCMI_Bridge_0_1_synth_1/MarsZX3_HDPYX_DCMI_Bridge_0_1.dcp C:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_HDPYX_DCMI_Bridge_0_1/MarsZX3_HDPYX_DCMI_Bridge_0_1.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub C:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_HDPYX_DCMI_Bridge_0_1/MarsZX3_HDPYX_DCMI_Bridge_0_1_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub C:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_HDPYX_DCMI_Bridge_0_1/MarsZX3_HDPYX_DCMI_Bridge_0_1_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim C:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_HDPYX_DCMI_Bridge_0_1/MarsZX3_HDPYX_DCMI_Bridge_0_1_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim C:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_HDPYX_DCMI_Bridge_0_1/MarsZX3_HDPYX_DCMI_Bridge_0_1_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force C:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.runs/MarsZX3_HDPYX_DCMI_Bridge_0_1_synth_1/MarsZX3_HDPYX_DCMI_Bridge_0_1.dcp C:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_HDPYX_DCMI_Bridge_0_1/MarsZX3_HDPYX_DCMI_Bridge_0_1.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force C:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.runs/MarsZX3_HDPYX_DCMI_Bridge_0_1_synth_1/MarsZX3_HDPYX_DCMI_Bridge_0_1_stub.v C:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_HDPYX_DCMI_Bridge_0_1/MarsZX3_HDPYX_DCMI_Bridge_0_1_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.runs/MarsZX3_HDPYX_DCMI_Bridge_0_1_synth_1/MarsZX3_HDPYX_DCMI_Bridge_0_1_stub.vhdl C:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_HDPYX_DCMI_Bridge_0_1/MarsZX3_HDPYX_DCMI_Bridge_0_1_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.runs/MarsZX3_HDPYX_DCMI_Bridge_0_1_synth_1/MarsZX3_HDPYX_DCMI_Bridge_0_1_sim_netlist.v C:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_HDPYX_DCMI_Bridge_0_1/MarsZX3_HDPYX_DCMI_Bridge_0_1_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force C:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.runs/MarsZX3_HDPYX_DCMI_Bridge_0_1_synth_1/MarsZX3_HDPYX_DCMI_Bridge_0_1_sim_netlist.vhdl C:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_HDPYX_DCMI_Bridge_0_1/MarsZX3_HDPYX_DCMI_Bridge_0_1_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir C:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.ip_user_files/ip/MarsZX3_HDPYX_DCMI_Bridge_0_1]} {
  catch { 
    file copy -force C:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_HDPYX_DCMI_Bridge_0_1/MarsZX3_HDPYX_DCMI_Bridge_0_1_stub.v C:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.ip_user_files/ip/MarsZX3_HDPYX_DCMI_Bridge_0_1
  }
}

if {[file isdir C:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.ip_user_files/ip/MarsZX3_HDPYX_DCMI_Bridge_0_1]} {
  catch { 
    file copy -force C:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_HDPYX_DCMI_Bridge_0_1/MarsZX3_HDPYX_DCMI_Bridge_0_1_stub.vhdl C:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.ip_user_files/ip/MarsZX3_HDPYX_DCMI_Bridge_0_1
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
