# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/fab/work/atise/trunk/projects/hdpyx_2019/updates_fab_1/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_gpio_0_0/MarsZX3_axi_gpio_0_0.xci
# IP: The module: 'MarsZX3_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/fab/work/atise/trunk/projects/hdpyx_2019/updates_fab_1/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_gpio_0_0/MarsZX3_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'MarsZX3_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/fab/work/atise/trunk/projects/hdpyx_2019/updates_fab_1/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_gpio_0_0/MarsZX3_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MarsZX3_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/fab/work/atise/trunk/projects/hdpyx_2019/updates_fab_1/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_gpio_0_0/MarsZX3_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MarsZX3_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/fab/work/atise/trunk/projects/hdpyx_2019/updates_fab_1/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_gpio_0_0/MarsZX3_axi_gpio_0_0.xci
# IP: The module: 'MarsZX3_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/fab/work/atise/trunk/projects/hdpyx_2019/updates_fab_1/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_gpio_0_0/MarsZX3_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'MarsZX3_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/fab/work/atise/trunk/projects/hdpyx_2019/updates_fab_1/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_gpio_0_0/MarsZX3_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MarsZX3_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/fab/work/atise/trunk/projects/hdpyx_2019/updates_fab_1/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_gpio_0_0/MarsZX3_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MarsZX3_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
