# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
}

set_msg_config  -severity {WARNING}  -suppress 
set_msg_config  -id {DRC 23-20}  -string {{CRITICAL WARNING: [DRC 23-20] Rule violation (IOSTDTYPE-1) IOStandard Type - I/O port CAM0_XCLK_N is Single-Ended but has an IOStandard of LVDS_25 which can only support Differential}}  -suppress 
set_msg_config  -id {DRC 23-20}  -string {{CRITICAL WARNING: [DRC 23-20] Rule violation (IOSTDTYPE-1) IOStandard Type - I/O port CAM0_XCLK_P is Single-Ended but has an IOStandard of LVDS_25 which can only support Differential}}  -suppress 
set_msg_config  -id {DRC 23-20}  -string {{CRITICAL WARNING: [DRC 23-20] Rule violation (IOSTDTYPE-1) IOStandard Type - I/O port CAM1_XYCLK_N is Single-Ended but has an IOStandard of LVDS_25 which can only support Differential}}  -suppress 
set_msg_config  -id {DRC 23-20}  -string {{CRITICAL WARNING: [DRC 23-20] Rule violation (IOSTDTYPE-1) IOStandard Type - I/O port CAM1_XYCLK_P is Single-Ended but has an IOStandard of LVDS_25 which can only support Differential}}  -suppress 
set_msg_config  -id {Synth 8-2029}  -string {{ERROR: [Synth 8-2029] formal data_bank_b_p has no actual or default value [E:/Vivado/MEB1/src/system_top_EB1.vhd:331]}}  -suppress 
set_msg_config  -id {Common 17-69}  -string {{ERROR: [Common 17-69] Command failed: Synthesis failed - please see the console or run log file for details}}  -suppress 
set_msg_config  -id {Timing 38-282}  -string {{CRITICAL WARNING: [Timing 38-282] The design failed to meet the timing requirements. Please see the timing summary report for details on the timing violations.}}  -suppress 
set_msg_config  -id {filemgmt 20-1788}  -string {{ERROR: [filemgmt 20-1788] Illegal access of HADGNode between graph update events.}}  -suppress 
set_msg_config  -id {filemgmt 56-23}  -string {{ERROR: [filemgmt 56-23] Illegal GUI graph access between updates.}}  -suppress 
set_msg_config  -id {Place 30-574}  -suppress 
set_msg_config  -id {BD 41-967}  -suppress 
set_msg_config  -id {IP_Flow 19-4965}  -suppress 
set_msg_config  -id {Common 17-55}  -suppress 
set_msg_config  -id {Common 17-1355}  -suppress 
set_msg_config  -id {Place 30-378}  -string {{ERROR: [Place 30-378] Input pin of input buffer i_system/selectio_bank_a/inst/ibufds_clk_inst has an illegal connection to a logic constant value.}}  -suppress 
set_msg_config  -id {BD 41-759}  -string {{CRITICAL WARNING: [BD 41-759] The input pins (listed below) are either not connected or do not have a source port, and they don't have a tie-off specified. These pins are tied-off to all 0's to avoid error in Implementation flow.
Please check your design and connect them as needed: 
/HDPyx_TPG_0/start
/HDPyx_TPG_1/start}}  -suppress 
set_msg_config  -id {DRC 23-20}  -string {{ERROR: [DRC 23-20] Rule violation (BIVC-1) Bank IO standard Vcc - Conflicting Vcc voltages in bank 35. For example, the following two ports in this bank have conflicting VCCOs:  
DATA_BANK_A_P[0] (LVCMOS18, requiring VCCO=1.800) and Led_N[0] (LVCMOS25, requiring VCCO=2.500)}}  -suppress 
set_msg_config  -id {Vivado_Tcl 4-23}  -string {{ERROR: [Vivado_Tcl 4-23] Error(s) found during DRC. Placer not run.}}  -suppress 

start_step init_design
set ACTIVE_STEP init_design
set rc [catch {
  create_msg_db init_design.pb
  set_param chipscope.maxJobs 3
  create_project -in_memory -part xc7z020clg484-1
  set_property design_mode GateLvl [current_fileset]
  set_param project.singleFileAddWarning.threshold 0
  set_property webtalk.parent_dir C:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.cache/wt [current_project]
  set_property parent.project_path C:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.xpr [current_project]
  set_property ip_repo_paths {
  C:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/ips/HDPyx_DDR_To_AXI_zybo
  C:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/ips/HDPyx_TPG
} [current_project]
  update_ip_catalog
  set_property ip_output_repo C:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.cache/ip [current_project]
  set_property ip_cache_permissions {read write} [current_project]
  set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
  add_files -quiet C:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.runs/MarsEB1_synth/system_top.dcp
  set_msg_config -source 4 -id {BD 41-1661} -limit 0
  set_param project.isImplRun true
  add_files C:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/MarsZX3.bd
  set_param project.isImplRun false
  read_xdc C:/FMa/ATISE/Development/design-16b_2CLK_3SENSORS_modif/design_mars/src/MarsZX3_EB1.xdc
  set_param project.isImplRun true
  link_design -top system_top -part xc7z020clg484-1
  set_param project.isImplRun false
  write_hwdef -force -file system_top.hwdef
  close_msg_db -file init_design.pb
} RESULT]
if {$rc} {
  step_failed init_design
  return -code error $RESULT
} else {
  end_step init_design
  unset ACTIVE_STEP 
}

start_step opt_design
set ACTIVE_STEP opt_design
set rc [catch {
  create_msg_db opt_design.pb
  opt_design 
  write_checkpoint -force system_top_opt.dcp
  create_report "MarsEB1_impl_opt_report_drc_0" "report_drc -file system_top_drc_opted.rpt -pb system_top_drc_opted.pb -rpx system_top_drc_opted.rpx"
  close_msg_db -file opt_design.pb
} RESULT]
if {$rc} {
  step_failed opt_design
  return -code error $RESULT
} else {
  end_step opt_design
  unset ACTIVE_STEP 
}

start_step place_design
set ACTIVE_STEP place_design
set rc [catch {
  create_msg_db place_design.pb
  if { [llength [get_debug_cores -quiet] ] > 0 }  { 
    implement_debug_core 
  } 
  place_design 
  write_checkpoint -force system_top_placed.dcp
  create_report "MarsEB1_impl_place_report_io_0" "report_io -file system_top_io_placed.rpt"
  create_report "MarsEB1_impl_place_report_utilization_0" "report_utilization -file system_top_utilization_placed.rpt -pb system_top_utilization_placed.pb"
  create_report "MarsEB1_impl_place_report_control_sets_0" "report_control_sets -verbose -file system_top_control_sets_placed.rpt"
  close_msg_db -file place_design.pb
} RESULT]
if {$rc} {
  step_failed place_design
  return -code error $RESULT
} else {
  end_step place_design
  unset ACTIVE_STEP 
}

start_step route_design
set ACTIVE_STEP route_design
set rc [catch {
  create_msg_db route_design.pb
  route_design 
  write_checkpoint -force system_top_routed.dcp
  create_report "MarsEB1_impl_route_report_drc_0" "report_drc -file system_top_drc_routed.rpt -pb system_top_drc_routed.pb -rpx system_top_drc_routed.rpx"
  create_report "MarsEB1_impl_route_report_methodology_0" "report_methodology -file system_top_methodology_drc_routed.rpt -pb system_top_methodology_drc_routed.pb -rpx system_top_methodology_drc_routed.rpx"
  create_report "MarsEB1_impl_route_report_power_0" "report_power -file system_top_power_routed.rpt -pb system_top_power_summary_routed.pb -rpx system_top_power_routed.rpx"
  create_report "MarsEB1_impl_route_report_route_status_0" "report_route_status -file system_top_route_status.rpt -pb system_top_route_status.pb"
  create_report "MarsEB1_impl_route_report_timing_summary_0" "report_timing_summary -max_paths 10 -file system_top_timing_summary_routed.rpt -pb system_top_timing_summary_routed.pb -rpx system_top_timing_summary_routed.rpx -warn_on_violation "
  create_report "MarsEB1_impl_route_report_incremental_reuse_0" "report_incremental_reuse -file system_top_incremental_reuse_routed.rpt"
  create_report "MarsEB1_impl_route_report_clock_utilization_0" "report_clock_utilization -file system_top_clock_utilization_routed.rpt"
  create_report "MarsEB1_impl_route_report_bus_skew_0" "report_bus_skew -warn_on_violation -file system_top_bus_skew_routed.rpt -pb system_top_bus_skew_routed.pb -rpx system_top_bus_skew_routed.rpx"
  close_msg_db -file route_design.pb
} RESULT]
if {$rc} {
  write_checkpoint -force system_top_routed_error.dcp
  step_failed route_design
  return -code error $RESULT
} else {
  end_step route_design
  unset ACTIVE_STEP 
}

start_step write_bitstream
set ACTIVE_STEP write_bitstream
set rc [catch {
  create_msg_db write_bitstream.pb
  set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
  catch { write_mem_info -force system_top.mmi }
  write_bitstream -force system_top.bit 
  catch { write_sysdef -hwdef system_top.hwdef -bitfile system_top.bit -meminfo system_top.mmi -file system_top.sysdef }
  catch {write_debug_probes -quiet -force system_top}
  catch {file copy -force system_top.ltx debug_nets.ltx}
  close_msg_db -file write_bitstream.pb
} RESULT]
if {$rc} {
  step_failed write_bitstream
  return -code error $RESULT
} else {
  end_step write_bitstream
  unset ACTIVE_STEP 
}

