# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_1SENSOR_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_vdma_0_1/MarsZX3_axi_vdma_0_1.xci
# IP: The module: 'MarsZX3_axi_vdma_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_1SENSOR_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_vdma_0_1/MarsZX3_axi_vdma_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'MarsZX3_axi_vdma_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_1SENSOR_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_vdma_0_1/MarsZX3_axi_vdma_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'MarsZX3_axi_vdma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_1SENSOR_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_vdma_0_1/MarsZX3_axi_vdma_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MarsZX3_axi_vdma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_1SENSOR_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_vdma_0_1/MarsZX3_axi_vdma_0_1.xci
# IP: The module: 'MarsZX3_axi_vdma_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_1SENSOR_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_vdma_0_1/MarsZX3_axi_vdma_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'MarsZX3_axi_vdma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_1SENSOR_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_vdma_0_1/MarsZX3_axi_vdma_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'MarsZX3_axi_vdma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/FMa/ATISE/Development/Clean_ENV/design-16b_2CLK_1SENSOR_modif/design_mars/Vdo/MarsZX3_EB1.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_vdma_0_1/MarsZX3_axi_vdma_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MarsZX3_axi_vdma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
